### ISSUE TITLE
CSP search does not load example problems

### ISSUE THREAD

**Issue by DexiongYung** [AISpace2/AISpace2#106]
**Step 1)** Go to `notebooks/csp/solving_csp_with_search.ipynb` 
**Step 2)** then go to Cell [26] and inside Cell [26] go to line #4 
"search_csp = DF_branch_and_bound(problem=Search_from_CSP(csp=csp_simple2))"
**Step 3)** Set "csp=" to one of the example csp problems which is in Cell [25]. 
**Step 4)** Run Cell [25] onward till graph appears on screen

It should load the example CSP but it currently just loads a single start node. To see a visual of what the examples should look like you can go to notebooks and check out csp_builder.ipynb and run that notebook and the examples will show up properly.

**Comment by Chenliang-Zhou** [comment]
I don't think this is a bug. We use top-down search for this and prune it on the way. try to Step it several times.
