### ISSUE TITLE
CSP search does not show multiple solutions

### ISSUE THREAD

**Issue by Chenliang-Zhou** [AISpace2/AISpace2#107]
In `notebook/solving_csp_with_search.ipynb`, run 
```search_csp = DF_branch_and_bound(problem=Search_from_CSP(csp=csp_simple1))```

it shows this:

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/39361141/61760116-4a450580-ad7f-11e9-931e-ab025b9fd0cb.png">

But when clicking `Step` or `Auto Solve`, nothing happens even though there is still something in the `Frontier`

**Comment by kirigiricloud** [comment]
This problem is also related to #68 , applying commit 48ac5c0 will also solve the problem of issue 68
