### ISSUE TITLE
Improving readability of csp/solving_csp_with_search

### ISSUE THREAD

**Issue by annazhelt** [AISpace2/AISpace2#12]
As the algorithm progresses graph becomes cluttered with a lot of nodes and becomes unreadable
![screen shot 2018-05-24 at 4 35 10 pm](https://user-images.githubusercontent.com/12523017/40518858-72edd4f6-5f71-11e8-92eb-966f7be408a9.png)

Suggestions:
- As number of nodes in graph grows, decrease the node size. Eventually the nodes can be circles with no text unless user chooses to expand node.
- All the nodes in any subtree start with the same assignment e.g. all nodes in the picture above start with 'two_down:...'. This makes it difficult to differentiate nodes. Node can either start with or only contain the assignment that differentiates it from its parent. There could be an option to set whether node contains the full assignment or just the assignment that differentiates it from its parent.
- Try a left to right instead of top down tree?

**Comment by Chenliang-Zhou** [comment]
They added an attribute called "show_full_domain" but did not implement it. We need to implement that.

**Comment by Chenliang-Zhou** [comment]
The tree search graph in forward_planning.ipynb also has this problem

**Comment by Chenliang-Zhou** [comment]
For the last point, I think we can keep the top-down tree structure.

**Comment by Chenliang-Zhou** [comment]
1. make the label smaller and align with arrows.
2. Try to avoid overlapping of arrows when A->B and also B->A
