### ISSUE TITLE
Add visualization options to more of the notebooks 

### ISSUE THREAD

**Issue by annazhelt** [AISpace2/AISpace2#13]
The csp/arc_consistency notebook has useful visualization options:
![screen shot 2018-05-24 at 4 56 16 pm](https://user-images.githubusercontent.com/12523017/40519228-6a247e86-5f73-11e8-9fd5-49b4d02bc8bc.png)

A lot of the other notebooks do not have these options. Add these options to the cells above any widget in any notebook.

**Comment by richard-chiang** [comment]
done. Pull Request raised
https://github.com/AISpace2/AISpace2/pull/18

**Comment by richard-chiang** [comment]
Done. Merged.
