### ISSUE TITLE
Compatibility with more recent versions of jupyterhub

### ISSUE THREAD

**Issue by dirkcgrunwald** [AISpace2/AISpace2#160]
I'm trying to build with jupyterlab 2..1.1 and getting the following conflicts.
Is there a work-around for this?

"aispace2@0.7.11" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.1.1 <2.2.0          >=1.0.0 <2.0.0 @jupyterlab/application
>=2.1.0 <2.2.0          >=1.0.0 <2.0.0 @jupyterlab/apputils
>=2.1.1 <2.2.0          >=1.0.0 <2.0.0 @jupyterlab/notebook

**Comment by lilycyf** [comment]
Hi, we are working on it and we will release the updated version by the end of next week.
