### ISSUE TITLE
Displaying widget: model not found

### ISSUE THREAD

**Issue by mantyni** [AISpace2/AISpace2#167]
Hi, 

I followed the AI Space 2 installation tutorial but the visualisations do not work for both, Linux or Windows machines. The only message that comes up on Jupyter Lab browser is: Error displaying widget: model not found. Can you advice how to fix this? 

Thanks

![Screenshot from 2020-12-30 13-59-19](https://user-images.githubusercontent.com/44416803/103355887-59b59b80-4aa7-11eb-8441-29700ce74db4.png)

**Comment by ZijiaZhang** [comment]
Can you show me what extensions are installed in Jupyter Lab? It can be found at the last tab on the left with a `puzzle` icon.

**Comment by mantyni** [comment]
Hi Ziija

> Can you show me what extensions are installed in Jupyter Lab? It can be found at the last tab on the left with a `puzzle` icon.

**Comment by mantyni** [comment]
Hi ZijiaZhang, 

Looks like only @jupyter-widgets/jupyterlab-manager is installed. I'm attaching the screenshot. 

Also after running installScripts.sh I get this: 
ValueError: 
"aispace2@0.8.11" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension      Package
>=3.0.0 <3.1.0          >=2.1.2 <3.0.0 @jupyterlab/application
>=3.0.0 <3.1.0          >=2.1.1 <3.0.0 @jupyterlab/apputils
>=3.0.0 <3.1.0          >=2.1.2 <3.0.0 @jupyterlab/notebook

Thanks

![Screenshot from 2021-01-01 14-38-40](https://user-images.githubusercontent.com/44416803/103440681-961bff80-4c3f-11eb-8014-408ede4d2313.png)

**Comment by ZijiaZhang** [comment]
It seems like your JupyterLab is not supported. What's the version of it? @lilycyf Can you also take a look?

**Comment by mantyni** [comment]
I have JupyterLab 3.0 which was installed by default using installScripts.sh as in AI Space tutorials.

This line is in instalScripts.sh, which gets latest JupyterLabs 3.0 with pip install (not compatible anymore):
`pip3 install --upgrade jupyterlab`

I've changed it to use the 2.2.9 version and it all works now:
`pip3 install jupyterlab==2.2.9`

Thanks
