### ISSUE TITLE
installScripts/installScripts.sh report a wrong version of Node.js

### ISSUE THREAD

**Issue by jcboyer** [AISpace2/AISpace2#180]
System:  Raspberry PI 4 8 Gig Raspberry Os 32 bit. Running off a terabyte SSD.

Executing: sh /home/pi/Documents/AISpace2-0.8.11/installScripts/installScripts.sh

shows this error:
Installing Jupyter labextension ...
An error occured.
ValueError: Please install nodejs >=12.0.0 before continuing. nodejs may be installed using conda or directly from the nodejs website.

--
Checking  nodejs --version ==> v12.22.1  Before executing SH above.
--
Not clear what I am missing.
Help is appreciated.

**Comment by ZijiaZhang** [comment]
👀

**Comment by ZijiaZhang** [comment]
Hi, I have tried to run this on my Pi and it worked. Jupyter should generate an error log when it fails. May I take look at that?

**Comment by ZijiaZhang** [comment]
I can take a closer look tomorrow/ during the weekend.

**Comment by jcboyer** [comment]
I will send the logs soon.
--------------------------------------------------------------------
Jerome Boyer

**Comment by ZijiaZhang** [comment]
You can also try the docker version here: https://github.com/ZijiaZhang/AISpace2/wiki#faq 
I added a force install option and hopfully can solve your problem. This also works on my Pi. Please let me know if there is any issue. 
I would also upload the docker image (ideally) later this week so everyone can work with it.

**Comment by jcboyer** [comment]
Thanks, I'll check it out.

I have reinstalled the RPI from scratch. It looks like there may have been
issues between Python 2 and 3 installs and the $PATH. After
--------------------------------------------------------------------
Jerome Boyer

**Comment by jcboyer** [comment]
Success!!! Thank you.
--------------------------------------------------------------------
Jerome Boyer
