### ISSUE TITLE
fix installation instruction

### ISSUE THREAD

**Issue by Chenliang-Zhou** [AISpace2/AISpace2#39]
fix installation instruction at https://aispace2.github.io/AISpace2/install.html

**Comment by HDW-ZHOU** [comment]
#36 is related

**Comment by HDW-ZHOU** [comment]
One major thing needing changing is that we now require them clone the project from AISpace2/AISpace2 instead of AISpace2/AIPython

**Comment by Chenliang-Zhou** [comment]
also the upgrade part

**Comment by Chenliang-Zhou** [comment]
different pages

**Comment by Chenliang-Zhou** [comment]
Just need to update instructions for JupyterHub

**Comment by ZijiaZhang** [comment]
JupiterHub have permission issue when try to install extensions.

"PermissionError: [Errno 1] Operation not permitted: '/opt/conda/share/jupyter/lab/staging/index.js'"

**Comment by ZijiaZhang** [comment]
May be need an update on windows python install.
It might be easier for users to install python using Microsoft Store.

**Comment by ZijiaZhang** [comment]
Current Issue with the installation instruction:

- If user used "pip install aispace2 --user", the installed version of aipython does not match the one in the repo.

Possible Solutions:

1. Use development build for installation. -> Package points
2. Update the aipython on web server. -> User cannot change the code for aipython (hard to access)
