### ISSUE TITLE
Improve BN frontend

### ISSUE THREAD

**Issue by Chenliang-Zhou** [AISpace2/AISpace2#79]
1. Make observation text and query text show on different lines, otherwise it would be confusing (see picture below). We should have 3 lines: 1st line: var name; 2nd line: observation value if the observation is made (don't abbreviate it as Obs, just make it Observation=c101); 3rd line: query result if it is queried. Also, make the 1st line (var name) bigger than 2nd and 3rd lines. You can show me how it looks like via slack and decide how larger it best be.
<img width="580" alt=" 2019-06-20 20 08 28" src="https://user-images.githubusercontent.com/39361141/59894885-24e76500-9397-11e9-9df7-c1909d92df10.png">

2. reset button should reset everything. currently it just clears the observation text, we need also to clear the query result (i.e. clears 2nd and 3rd lines)

3. When the user makes an observation, the probability result also comes out. This should not come out until the user go back to query mode and click on a variable to query. Also, even if the user observe on a variable that was already queried (i.e., it is showing the probability), we should also clear the query result (instead of update and show it directly), otherwise it would be confusing.

4. replace the observe pop out window with the check box appearing at the bottom of the canvas, like what is supposed to be implemented in CSP domain splitting prompt in #56.

5. Add a visualization bar graph

**Comment by kirigiricloud** [comment]
6. After submit in CSP and Bayes, the checkboxes and selectbox will disappear
7. change checkbox to select in Bayes, using checkbox in CSP
8. After you submit, the query results will update automatically

**Comment by Chenliang-Zhou** [comment]
1. When making first observation, the line width of the nodes weirdly change.
2. The result of observation is not shown.
3. In query mode, need to click many times....
